<template><div><h1 id="frontmatter-title" tabindex="-1"><a class="header-anchor" href="#frontmatter-title" aria-hidden="true">#</a> {{ $frontmatter.title }}</h1>
<blockquote>
<p>{{ $frontmatter.description }}</p>
</blockquote>
<p>There is <strong>a lot</strong> of literature concerning the current state of higher education, and most of it is usually concerning the outrageous price. But I fear we may have an even bigger issue (that in many ways in correlated to the price issue) on our hands.</p>
<p>Yesterday, in the middle of my daily YouTube binge I stubbled upon <a href="https://youtu.be/7J-wCHDJYmo" target="_blank" rel="noopener noreferrer">a talk by Malcom Gladwell given at Google Zeitgeist<ExternalLinkIcon/></a>. He correlated SAT scores of incoming students pursuing stem degrees at 4 year colleges with their likelihood of graduating with a STEM degree. He compared students at Hartwick College to students at Harvard University, and found that for both institutions the students in the top quarter of class rankings where very likely to graduate with a stem degree while those in the bottom quarter where very unlikely to graduate with a STEM degree and much more likely to drop out of the program. This is despite the fact that the bottom quarter of students at Harvard University had the same SAT scores as the top quarter of students at Hartwick. In Summary, his argument was that completing a degree is not a measure of Intelligence but a measure of your class ranking. Malcolm Gladwell thinks you should go to Hardwick instead of Harvard to ensure you are in the top of your class and therefore more likely to graduate with the STEM degree you initially intended on pursuing. I disagree.</p>
<p>Now, I realize Malcolm Gladwell intended for this opinion of his to be controversial. From what I know about him, he likes to make unconventional arguments, play devils advocate, and highlight new ways of thinking that go against the conventional wisdom. I believing questioning the world in this way is extremely beneficial for everyone. Question Everything. This is not an article to bash Malcolm Gladwell, I'm actually a fan of his work, and find him to be a skilled and entertaining thinker and storyteller. Despite disagreeing with the logical foundations of his argument I do think he has a compelling conclusion. More broadly I am a fan of much of his work (particularly his podcast, Revisionist History) and really enjoy how the way he presents his topics inspires me to contemplate them further on my own.</p>
<p>Okay, now onto the interesting stuff.</p>
<h2 id="my-main-problem-with-both-harvard-and-malcolm-gladwell-s-argument-is-ego" tabindex="-1"><a class="header-anchor" href="#my-main-problem-with-both-harvard-and-malcolm-gladwell-s-argument-is-ego" aria-hidden="true">#</a> My main problem with both Harvard and Malcolm Gladwell's argument is <strong>Ego</strong>.</h2>
<ol>
<li>I agree with the conclusion, &quot;Don't go to Harvard&quot;</li>
</ol>
<p>Far too many students who idolize the Ivy League and extremely competitive institutions. Don't get me wrong, these institutions have enormous value for society as a whole, but I believe the value they provide to individuals is incredibly overblown and only serves a very particular type of student. Far too often students apply to institutions on the standard of name recognition alone, with very little knowledge of what attending a school like this actually means for them and their career.</p>
<ol start="2">
<li>But I also disagree with Gladwell that you should go to an institution where you are more likely to be in the top of your class</li>
</ol>
<blockquote>
<p>Comfort is the enemy of progress
- P. T. Barnum</p>
</blockquote>
<p>While being a &quot;big fish in a small pond&quot; might help you stand out and keep you motivated to finish your degree, I personally feel it will lead to stunted personal development. If you are in an environment where you do not have to struggle, you aren't going to be maximizing your personal growth. Being challenged and sometimes failing is an essential learning experience. Dealing with failure is essential to resiliency and success in the workforce. If you attend an institution where you are not going to be challenged by your peers and your professors, how are you going to know how to handle those situations outside of the academic setting?  If you are too certain of your ability to be the best and exceed in your small pond, your ego will be shattered when encountering something you don't know or someone who knows way more than you when you reach the ocean. <strong>Students should not be afraid to fail. Students should not be satisfied by being comfortable at the top of the class.</strong></p>
<h2 id="an-unsolvable-conundrum" tabindex="-1"><a class="header-anchor" href="#an-unsolvable-conundrum" aria-hidden="true">#</a> An Unsolvable Conundrum</h2>
<p>While choosing a school where you will be in the middle of the class seems like the most logical and simple solution, This problem has much broader implications within academia and the psychology of individuals as a whole.</p>
<h3 id="being-okay-with-not-being-the-best" tabindex="-1"><a class="header-anchor" href="#being-okay-with-not-being-the-best" aria-hidden="true">#</a> Being okay with not being the best</h3>
<p>I think the most terrifying implication of Gladwell's argument is the notion that students who are closer to the bottom their class in terms of inherent mathematical skill are so likely to give up on pursuing a STEM degree. It's understandable why this is the case though, if you feel that you are not able to be a competitive candidate amongst your peers why would you continue trying? Except, being successful in technology requires many more skills than simply mathematical and technical ability. Our standards for evaluating and comparing students is broken, and limits the pool of candidates for a position to those with a very narrow skill set. We  are also encouraging students to avoid challenges and , instead encouraging them to chose pathways that do not challenge them. But challenges are the path to growth, and by avoiding them, we are not producing resilient, well-rounded candidates.</p>
<h3 id="ego-in-academia" tabindex="-1"><a class="header-anchor" href="#ego-in-academia" aria-hidden="true">#</a> Ego in Academia</h3>
<p><a href="https://www.cs.rice.edu/~vardi/" target="_blank" rel="noopener noreferrer">Moshe Vardi<ExternalLinkIcon/></a> also had some great things to say on this topic in <a href="http://www.changingacademiclife.com/blog/2019/3/31/moshe-vardi" target="_blank" rel="noopener noreferrer">this podcast<ExternalLinkIcon/></a>. Make sure to check out part one of the podcast as well.</p>
<p>We train professors to be very career oriented (and self obsessed) and therefore they fail in their primary role as a public servant. &quot;Publish or perish&quot; is the motto for college faculty, and they are therefore forced to place enormous emphasis on their personal research.</p>
<p>We are also simultaneously expecting much more and much less of our students. We expect students to have an enormous and diverse portfolio of experiences, but we don't want to see any weaknesses (such as a low grade in a class). Therefore, students are less likely to seek out classes that expose their weaknesses and truly challenge themselves, in fear that a less-than-spectacular grade will reflect poorly on them and negatively impact their future opportunities. Students will not be taking the classes they <strong>need</strong> to be taking, the ones that challenge them to think in new ways and expand their breadth of knowledge, and most importantly, teach them how to fail and get back up. We have structured academia to encourage this type of decision making.</p>
</div></template>


